spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://httpbin.org:80
        predicates:
        - Path=/**
#        filters:
#        - PrefixPath=/mypath
#        predicates:
#        - Cookie=mycookie,mycookievalue