eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:${EUREKA_PORT:8761}/eureka}
    registerWithEureka: true

server:
  port: ${GATEWAY_PORT:9090}
 
spring:
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      enabled: true
      import-check: false
  config:
    import: optional:configserver:tuputamadre
#  profiles:
#    active: default
    